local function nyi(name)
    return function() error(name .. " not yet implemented") end
end

world = {}
world.getTime = nyi("getTime")
world.getItemStatsFromId = nyi("getItemStatsFromId")
world.isItemOnField = nyi("isItemOnField")
world.getItemOnField = nyi("getItemOnField")
world.changeItem = nyi("changeItem")
world.getPlayersInRangeOf = nyi("getPlayersInRangeOf")
world.erase = nyi("erase")
world.gfx = nyi("gfx")
world.getPlayersOnline = nyi("getPlayersOnline")
world.swap = nyi("swap")
world.makeSound = nyi("makeSound")
world.getItemName = nyi("getItemName")
world.getField = nyi("getField")
world.isCharacterOnField = nyi("isCharacterOnField")
world.getCharacterOnField = nyi("getCharacterOnField")
world.createItemFromId = nyi("createItemFromId")
world.getMonstersInRangeOf = nyi("getMonstersInRangeOf")
world.isPersistentAt = nyi("isPersistentAt")
world.makePersistentAt = nyi("makePersistentAt")
world.broadcast = nyi("broadcast")
world.createMonster = nyi("createMonster")